# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "skinny-terraform-vpc"
    dynamodb_table = "terraform-lock"
    encrypt        = true
    key            = "test/us-west-1/vpc/terraform.tfstate"
    region         = "ap-southeast-2"
  }
}
